apiVersion: v1
kind: Service
metadata:
  name: jarvis-bot-ui-service
  labels:
    app: jarvis-ui-bot
spec:
  type: NodePort
  ports:
  - port: 80
    targetPort: 80
    nodePort: 34580
    protocol: TCP
    name: http
  selector:
    app: jarvis-ui-bot
    
apiVersion:  apps/v1
kind: Deployment
metadata:
  name: jarvis-ui-bot-engine
  labels:
    app: jarvis-ui-bot
spec:
  selector:
    matchLabels:
        app: jarvis-ui-bot
  replicas: 1
  template:
    metadata:
      labels:
        app: jarvis-ui-bot
    spec:
      containers:
      - name: jarvis-ui-bot-engine
        image: msr-aws-d.abbvienet.com/cwcm-admp-dev/admp-jarvis:jarvis-fnt_V0.1
        resources:
          requests:
            cpu: "100m"
        imagePullPolicy: Always
        ports:
        - containerPort: 80
        env:
        - name: VERSION
          value: "v1"
        - name: METADATA
          value: "dev"
        - name: SPRING_PROFILES_ACTIVE
          value: "dev"  
          
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: jarvis-ui-bot-engine
spec:
  ingressClassName: nginx-default
  rules:
    - host: jarvis-bot-app.aws-k8s-d.abbvienet.com
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: jarvis-bot-ui-service
                port:
                  number: 80
