name: Deploy to MKE

on:
  push:
    branches:
      - "feature/*"   # run on all feature branches
  workflow_dispatch:

jobs:
  deploy:
    runs-on: self-hosted
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up kubeconfig
        run: |
          mkdir -p $HOME/.kube
          echo "${{ secrets.KUBECONFIG_DATA }}" > $HOME/.kube/config

      - name: Azure Container Registry login (MSR)
        run: |
          echo "${{ secrets.MSR_PASSWORD }}" | docker login msr.azurecr.io -u "${{ secrets.MSR_USERNAME }}" --password-stdin

      - name: Deploy backend
        run: |
          kubectl apply -f K8s/backend.yml
          kubectl apply -f K8s/backend-ingress.yml

      - name: Deploy frontend
        run: |
          kubectl apply -f K8s/frontend.yml
          kubectl apply -f K8s/frontend-ingress.yml

